#!/usr/bin/env python3
"""
Simple Mode 1 Analysis - Suricata Rule-Based Detection
Counts alert events generated by Suricata rules
"""

import json
import sys
from collections import defaultdict

def analyze_mode1_simple(eve_file):
    """Simple Mode 1 analysis - just count alerts vs HTTP events"""
    
    total_http = 0
    total_alerts = 0
    alert_signatures = defaultdict(int)
    xss_alerts = 0
    
    try:
        with open(eve_file, 'r') as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                    
                try:
                    event = json.loads(line)
                    event_type = event.get("event_type", "")
                    
                    if event_type == "http":
                        total_http += 1
                        
                    elif event_type == "alert":
                        total_alerts += 1
                        alert_data = event.get("alert", {})
                        signature = alert_data.get("signature", "Unknown")
                        alert_signatures[signature] += 1
                        
                        # Check if it's XSS-related
                        if any(keyword in signature.lower() for keyword in ["xss", "script", "javascript", "injection"]):
                            xss_alerts += 1
                            
                except json.JSONDecodeError:
                    continue
                    
    except FileNotFoundError:
        print(f"❌ Error: File not found: {eve_file}")
        return
    except Exception as e:
        print(f"❌ Error reading file: {e}")
        return
    
    # Print results
    print("=" * 60)
    print("📊 MODE 1 SURICATA ANALYSIS SUMMARY")
    print("=" * 60)
    print(f"Total HTTP Requests: {total_http}")
    print(f"Alert Events Generated: {total_alerts}")
    
    if total_http > 0:
        detection_rate = (total_alerts / total_http) * 100
        print(f"Detection Rate: {detection_rate:.1f}%")
    else:
        print("Detection Rate: N/A (no HTTP events)")
    
    print()
    print("🔍 SURICATA RULE ANALYSIS:")
    print(f"   Rule Detection: {'Active' if total_alerts > 0 else 'Inactive'}")
    print(f"   XSS-related Alerts: {xss_alerts}")
    print(f"   Total Rule Triggers: {total_alerts}")
    
    if alert_signatures:
        print()
        print("📋 ALERT SIGNATURES:")
        sorted_alerts = sorted(alert_signatures.items(), key=lambda x: x[1], reverse=True)
        for signature, count in sorted_alerts[:10]:  # Show top 10
            print(f"   {count:3d}x {signature}")
    else:
        print()
        print("⚠️  No alerts detected - check Suricata rules configuration")
    
    print()
    print("📊 DETECTION RATE ANALYSIS:")
    print(f"   Rate: {detection_rate:.1f}% of HTTP traffic triggered alerts" if total_http > 0 else "   No HTTP traffic to analyze")
    print(f"   Triggered: {total_alerts}")
    print(f"   Total HTTP: {total_http}")
    print(f"   No Alerts: {total_http - total_alerts}")

def main():
    if len(sys.argv) != 2:
        print("Usage: python3 analyze_mode1_simple.py <eve.json>")
        sys.exit(1)
    
    eve_file = sys.argv[1]
    analyze_mode1_simple(eve_file)

if __name__ == "__main__":
    main()
